feat(deps): added redux-toolkit with sample and update setup

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,4 +1,12 @@
 #!/usr/bin/env sh
 
 echo "🔍 Validating commit message..."
+
 pnpm exec commitlint --edit "$1"
+
+if [ $? -eq 0 ]; then
+  echo "✅ Commit message is valid."
+else
+  echo "❌ Commit message is invalid. Please follow the commit message conventions."
+  exit 1
+fi
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,16 @@
 #!/usr/bin/env sh
 
-echo "🧹 Running pre-commit checks with lint-staged..."
-pnpm exec lint-staged
+echo "🧹 Running pre-commit checks..."
+
+echo "Current working directory: $(pwd)"
+
+pnpm run type-check
+pnpm run lint 
+pnpm run format
+
+if [ $? -eq 0 ]; then
+  echo "✅ Pre-commit checks passed successfully!"
+else
+  echo "❌ Pre-commit checks failed. Please fix the issues and try again."
+  exit 1
+fi
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,4 +5,9 @@ echo "🚀 Running pre-push checks..."
 pnpm run lint 
 pnpm run format
 
-echo "✅ Lint and format passed. Proceeding with push."
+if [ $? -eq 0 ]; then
+  echo "✅ Lint and format passed. Proceeding with push."
+else
+  echo "❌ Pre-push checks failed. Please fix the issues before pushing."
+  exit 1
+fi
